# generated by datamodel-codegen:
#   filename:  openapi_spec.yaml
#   timestamp: 2024-11-06T12:58:18+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class AnnualIncome:
    cpr: str | None = None
    year: int | None = None
    salary: float | None = None
    social_benefit_income: float | None = None
    retirement_pension_income: float | None = None
    disability_pension_income: float | None = None
    ignored_benefits: float | None = None
    occupational_benefit: float | None = None
    foreign_pension_income: float | None = None
    subsidy_foreign_pension_income: float | None = None
    dis_gis_income: float | None = None
    other_a_income: float | None = None
    deposit_interest_income: float | None = None
    bond_interest_income: float | None = None
    other_interest_income: float | None = None
    education_support_income: float | None = None
    care_fee_income: float | None = None
    alimony_income: float | None = None
    foreign_dividend_income: float | None = None
    foreign_income: float | None = None
    free_journey_income: float | None = None
    group_life_income: float | None = None
    rental_income: float | None = None
    other_b_income: float | None = None
    free_board_income: float | None = None
    free_lodging_income: float | None = None
    free_housing_income: float | None = None
    free_phone_income: float | None = None
    free_car_income: float | None = None
    free_internet_income: float | None = None
    free_boat_income: float | None = None
    free_other_income: float | None = None
    other_debt_interest_income: float | None = None
    pension_payment_income: float | None = None
    catch_sale_market_income: float | None = None
    catch_sale_factory_income: float | None = None
    account_extraord_entries_income: float | None = None
    account_business_interest: float | None = None
    account_business_interest_income: float | None = None
    account_business_interest_deduct: float | None = None
    account_tax_result: float | None = None
    account_share_business_percentage: float | None = None
    account_share_business_amount: float | None = None
    shareholder_dividend_income: float | None = None


@dataclass
class ExpectedIncome:
    cpr: str | None = None
    year: int | None = None
    valid_from: str | None = None
    do_expect_a_income: bool | None = None
    capital_income: float | None = None
    education_support_income: float | None = None
    care_fee_income: float | None = None
    alimony_income: float | None = None
    benefits_income: float | None = None
    other_b_income: float | None = None
    gross_business_income: float | None = None
    catch_sale_factory_income: float | None = None
    catch_sale_market_income: float | None = None
    bussiness_interest_income: float | None = None
    extraordinary_bussiness_income: float | None = None


@dataclass
class MonthlyIncome:
    """
    Specifies that the type is a data contract and can be serialized and
    deserialized by the DataContractSerializer.
    """

    cpr: str | None = None
    year: int | None = None
    month: int | None = None
    salary_income: float | None = None
    catchsale_income: float | None = None
    public_assistance_income: float | None = None
    alimony_income: float | None = None
    dis_gis_income: float | None = None
    retirement_pension_income: float | None = None
    disability_pension_income: float | None = None
    ignored_benefits_income: float | None = None
    employer_paid_gl_pension_income: float | None = None
    foreign_pension_income: float | None = None
    civil_servant_pension_income: float | None = None
    other_pension_income: float | None = None


@dataclass
class TaxInformation:
    cpr: str | None = None
    year: int | None = None
    tax_scope: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    tax_municipality_number: str | None = None
    cpr_municipality_code: str | None = None
    cpr_municipality_name: str | None = None
    region_number: str | None = None
    region_name: str | None = None
    district_name: str | None = None


@dataclass
class ServiceListResponseAnnualIncome:
    """
    Represents a generic class for a service list response containing items of type T.
    For a singular response data object use ServiceResponse.
    """

    data: list[AnnualIncome] | None = None
    message: str | None = None
    chunk: int | None = None
    chunk_size: int | None = None
    total_chunks: int | None = None
    total_records_in_chunks: int | None = None


@dataclass
class ServiceListResponseExpectedIncome:
    """
    Represents a generic class for a service list response containing items of type T.
    For a singular response data object use ServiceResponse.
    """

    data: list[ExpectedIncome] | None = None
    message: str | None = None
    chunk: int | None = None
    chunk_size: int | None = None
    total_chunks: int | None = None
    total_records_in_chunks: int | None = None


@dataclass
class ServiceListResponseMonthlyIncome:
    """
    Represents a generic class for a service list response containing items of type T.
    For a singular response data object use ServiceResponse.
    """

    data: list[MonthlyIncome] | None = None
    message: str | None = None
    chunk: int | None = None
    chunk_size: int | None = None
    total_chunks: int | None = None
    total_records_in_chunks: int | None = None


@dataclass
class ServiceListResponseTaxInformation:
    """
    Represents a generic class for a service list response containing items of type T.
    For a singular response data object use ServiceResponse.
    """

    data: list[TaxInformation] | None = None
    message: str | None = None
    chunk: int | None = None
    chunk_size: int | None = None
    total_chunks: int | None = None
    total_records_in_chunks: int | None = None


@dataclass
class ServiceListResponseString:
    """
    Represents a generic class for a service list response containing items of type T.
    For a singular response data object use ServiceResponse.
    """

    data: list[str] | None = None
    message: str | None = None
    chunk: int | None = None
    chunk_size: int | None = None
    total_chunks: int | None = None
    total_records_in_chunks: int | None = None
