version = 1
SPDX-PackageName = "Beskæftigelsestilskud"
SPDX-PackageSupplier = "Magenta ApS <info@magenta.dk>"

[[annotations]]
path = ["REUSE.toml", "**suila/logo**", "**suila/favicon.ico", "suila/**/migrations/**", "suila/suila/integrations/eskat/responses/*", "log/**", "dev-environment/**", "**README.md", "dev-idp/**", "rfc/**", "data/**", "suila/suila/tests/test.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Magenta ApS <info@magenta.dk>"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "suila/suila/static/jquery/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 OpenJS Foundation and jQuery contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["suila/suila/static/bootstrap/**.map", "suila/suila/static/bootstrap-icons/**.svg", "suila/suila/static/bootstrap-icons/font/fonts/**", "suila/suila/static/bootstrap-icons/font/bootstrap-icons.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)"
SPDX-License-Identifier = "MIT"
