# Generated by Django 5.0.4 on 2024-07-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf', '0001_initial'),
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonYearEstimateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_engine', models.CharField(max_length=100)),
                ('offset_percent', models.DecimalField(decimal_places=2, max_digits=7)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personyear')),
            ],
            options={
                'unique_together': {('person_year', 'estimation_engine')},
            },
        ),
    ]
