entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2

providers:
  file:
    filename: "/etc/traefik/dynamic/bf.yml"
    watch: true

accessLog:
  format: "json"
