# Generated by Django 5.0.4 on 2024-09-13 12:27

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvr', models.PositiveIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='CVR-nummer')),
                ('name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.TextField(help_text='CPR nummer', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='CPR nummer')),
                ('name', models.TextField(blank=True, null=True)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_line_3', models.TextField(blank=True, null=True)),
                ('address_line_4', models.TextField(blank=True, null=True)),
                ('address_line_5', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardWorkBenefitCalculationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_rate_percent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('personal_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('standard_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_benefit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scaledown_rate_percent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('scaledown_ceiling', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_reason', models.TextField(null=True)),
                ('cpr', models.TextField(db_index=True, help_text='CPR nummer', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='CPR nummer')),
                ('name', models.TextField(blank=True, null=True)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_line_3', models.TextField(blank=True, null=True)),
                ('address_line_4', models.TextField(blank=True, null=True)),
                ('address_line_5', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_entries', to='bf.person')),
            ],
            options={
                'verbose_name': 'historical person',
                'verbose_name_plural': 'historical persons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_estimation_engine_a', models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned'), ('SelfReportedEngine', 'Estimering udfra forskudsopgørelsen')], default='InYearExtrapolationEngine', max_length=100, null=True)),
                ('preferred_estimation_engine_b', models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned'), ('SelfReportedEngine', 'Estimering udfra forskudsopgørelsen')], default='InYearExtrapolationEngine', max_length=100, null=True)),
                ('stability_score_a', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('stability_score_b', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(verbose_name='Dato')),
                ('municipality_code', models.IntegerField(blank=True, null=True)),
                ('municipality_name', models.TextField(blank=True, null=True)),
                ('fully_tax_liable', models.BooleanField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('amount_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('benefit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_year_benefit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_year_benefit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prior_benefit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personyear')),
            ],
        ),
        migrations.CreateModel(
            name='FinalBIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personyear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonYearAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('renteindtægter', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('uddannelsesstøtte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('honorarer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('underholdsbidrag', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('andre_b', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('brutto_b_før_erhvervsvirk_indhandling', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('erhvervsindtægter_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('e2_indhandling', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('brutto_b_indkomst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='bf.personyear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonYearEstimateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_engine', models.CharField(max_length=100)),
                ('income_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('mean_error_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('rmse_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personyear')),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessedYearlyBIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('person_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personyear')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('calculation_method_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('calculation_method_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='personyear',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.year'),
        ),
        migrations.CreateModel(
            name='MonthlyBIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.employer', verbose_name='Indhandler')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.person')),
                ('person_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personmonth')),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], include=('id', 'person', 'month', 'year', 'person_month', 'amount', 'trader'), name='MonthlyBIncomeReport_person'), models.Index(fields=['year'], include=('id', 'person', 'month', 'person_month', 'amount', 'trader'), name='MonthlyBIncomeReport_year'), models.Index(fields=['month'], include=('id', 'person', 'year', 'person_month', 'amount', 'trader'), name='MonthlyBIncomeReport_month')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.employer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.person')),
                ('person_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bf.personmonth')),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], include=('id', 'person', 'month', 'year', 'person_month', 'amount', 'employer'), name='MonthlyAIncomeReport_person'), models.Index(fields=['year'], include=('id', 'person', 'month', 'person_month', 'amount', 'employer'), name='MonthlyAIncomeReport_year'), models.Index(fields=['month'], include=('id', 'person', 'year', 'person_month', 'amount', 'employer'), name='MonthlyAIncomeReport_month')],
            },
        ),
        migrations.CreateModel(
            name='IncomeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned'), ('SelfReportedEngine', 'Estimering udfra forskudsopgørelsen')], max_length=100)),
                ('income_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('estimated_year_result', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_year_result', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('person_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bf.personmonth')),
            ],
            options={
                'unique_together': {('engine', 'person_month', 'income_type')},
            },
        ),
        migrations.AddIndex(
            model_name='personmonth',
            index=models.Index(fields=['month'], name='bf_personmo_month_115b48_idx'),
        ),
        migrations.AddIndex(
            model_name='personmonth',
            index=models.Index(fields=['municipality_code'], name='bf_personmo_municip_8c1c35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personmonth',
            unique_together={('person_year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='personyearestimatesummary',
            unique_together={('person_year', 'estimation_engine', 'income_type')},
        ),
        migrations.AddIndex(
            model_name='personyear',
            index=models.Index(fields=['person', 'year'], name='bf_personye_person__6424e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personyear',
            unique_together={('person', 'year')},
        ),
    ]
