# Generated by Django 5.0.4 on 2024-06-04 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(verbose_name='Dato')),
                ('cpr', models.TextField(help_text='CPR nummer', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='CPR nummer')),
                ('name', models.TextField(blank=True, null=True)),
                ('municipality_code', models.IntegerField(blank=True, null=True)),
                ('municipality_name', models.TextField(blank=True, null=True)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_line_3', models.TextField(blank=True, null=True)),
                ('address_line_4', models.TextField(blank=True, null=True)),
                ('address_line_5', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['cpr'],
                'unique_together': {('cpr', 'import_date')},
                'index_together': {('cpr', 'import_date')},
            },
        ),
    ]
