# Generated by Django 5.0.4 on 2024-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='preferred_estimation_engine',
            field=models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incomeestimate',
            name='engine',
            field=models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_estimation_engine',
            field=models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned')], max_length=100, null=True),
        ),
    ]
