# Generated by Django 5.0.4 on 2024-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bf', '0002_alter_historicalperson_preferred_estimation_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmonth',
            name='actual_year_benefit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='preferred_estimation_engine',
            field=models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned')], default='SameAsLastMonthEngine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_estimation_engine',
            field=models.CharField(choices=[('InYearExtrapolationEngine', 'Ekstrapolation af beløb for måneder i indeværende år'), ('TwelveMonthsSummationEngine', 'Summation af beløb for de seneste 12 måneder'), ('SameAsLastMonthEngine', 'Ekstrapolation af beløb for den seneste måned')], default='SameAsLastMonthEngine', max_length=100, null=True),
        ),
    ]
