# Generated by Django 5.0.4 on 2024-11-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0007_monthlyaincomereport_alimony_income_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "social_benefit_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "retirement_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "disability_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "ignored_benefits",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "occupational_benefit",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "foreign_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "subsidy_foreign_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "dis_gis_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "other_a_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "deposit_interest_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "bond_interest_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "other_interest_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "education_support_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "care_fee_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "alimony_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "foreign_dividend_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "foreign_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_journey_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "group_life_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "rental_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "other_b_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_board_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_lodging_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_housing_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_phone_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_car_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_internet_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_boat_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "free_other_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "other_debt_interest_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "pension_payment_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "catch_sale_market_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "catch_sale_factory_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_extraord_entries_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_business_interest",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_business_interest_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_business_interest_deduct",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_tax_result",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_share_business_percentage",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "account_share_business_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "shareholder_dividend_income",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                (
                    "person_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bf.personyear"
                    ),
                ),
            ],
        ),
    ]
