# Generated by Django 5.1.3 on 2024-11-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0011_dataload_annualincome_load_employer_load_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalfinalbincomereport",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalfinalbincomereport",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfinalbincomereport",
            name="person_year",
        ),
        migrations.RemoveField(
            model_name="historicalselfassessedyearlybincome",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalselfassessedyearlybincome",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalselfassessedyearlybincome",
            name="person_year",
        ),
        migrations.RemoveField(
            model_name="selfassessedyearlybincome",
            name="person_year",
        ),
        migrations.DeleteModel(
            name="FinalBIncomeReport",
        ),
        migrations.DeleteModel(
            name="HistoricalFinalBIncomeReport",
        ),
        migrations.DeleteModel(
            name="HistoricalSelfAssessedYearlyBIncome",
        ),
        migrations.DeleteModel(
            name="SelfAssessedYearlyBIncome",
        ),
    ]
