# Generated by Django 5.1.3 on 2024-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0013_historicalpersonyear_tax_scope_personyear_tax_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeestimate",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="personyearestimatesummary",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
