# Generated by Django 5.1.3 on 2024-11-19 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0014_incomeestimate_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalfinalsettlement",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalfinalsettlement",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfinalsettlement",
            name="load",
        ),
        migrations.RemoveField(
            model_name="historicalfinalsettlement",
            name="person_year",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="underholdsbidrag",
            new_name="alimony_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="brutto_b_indkomst",
            new_name="brutto_b_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="renteindtægter",
            new_name="capital_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="honorarer",
            new_name="care_fee_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="uddannelsesstøtte",
            new_name="education_support_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="brutto_b_før_erhvervsvirk_indhandling",
            new_name="gross_business_income",
        ),
        migrations.RenameField(
            model_name="historicalpersonyearassessment",
            old_name="andre_b",
            new_name="other_b_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="underholdsbidrag",
            new_name="alimony_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="brutto_b_indkomst",
            new_name="brutto_b_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="renteindtægter",
            new_name="capital_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="honorarer",
            new_name="care_fee_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="uddannelsesstøtte",
            new_name="education_support_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="brutto_b_før_erhvervsvirk_indhandling",
            new_name="gross_business_income",
        ),
        migrations.RenameField(
            model_name="personyearassessment",
            old_name="andre_b",
            new_name="other_b_income",
        ),
        migrations.RemoveField(
            model_name="historicalpersonyearassessment",
            name="e2_indhandling",
        ),
        migrations.RemoveField(
            model_name="historicalpersonyearassessment",
            name="erhvervsindtægter_sum",
        ),
        migrations.RemoveField(
            model_name="personyearassessment",
            name="e2_indhandling",
        ),
        migrations.RemoveField(
            model_name="personyearassessment",
            name="erhvervsindtægter_sum",
        ),
        migrations.AddField(
            model_name="annualincome",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="person_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_income_statements",
                to="bf.personyear",
            ),
        ),
        migrations.DeleteModel(
            name="FinalSettlement",
        ),
        migrations.DeleteModel(
            name="HistoricalFinalSettlement",
        ),
    ]
