# Generated by Django 5.1.3 on 2024-11-25 09:48

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0015_remove_historicalfinalsettlement_history_relation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="load",
        ),
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="person",
        ),
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="person_month",
        ),
        migrations.RemoveField(
            model_name="historicalmonthlybincomereport",
            name="trader",
        ),
        migrations.RemoveField(
            model_name="monthlyaincomereport",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="monthlyaincomereport",
            name="load",
        ),
        migrations.RemoveField(
            model_name="monthlyaincomereport",
            name="person",
        ),
        migrations.RemoveField(
            model_name="monthlyaincomereport",
            name="person_month",
        ),
        migrations.RemoveField(
            model_name="monthlybincomereport",
            name="load",
        ),
        migrations.RemoveField(
            model_name="monthlybincomereport",
            name="person",
        ),
        migrations.RemoveField(
            model_name="monthlybincomereport",
            name="person_month",
        ),
        migrations.RemoveField(
            model_name="monthlybincomereport",
            name="trader",
        ),
        migrations.CreateModel(
            name="MonthlyIncomeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("a_income", models.DecimalField(decimal_places=2, max_digits=12)),
                ("b_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "salary_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "catchsale_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "public_assistance_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "alimony_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "dis_gis_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "retirement_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "disability_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "ignored_benefits_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "employer_paid_gl_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "foreign_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "civil_servant_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "other_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "capital_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bf.dataload",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bf.person"
                    ),
                ),
                (
                    "person_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bf.personmonth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMonthlyIncomeReport",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("history_change_reason", models.TextField(null=True)),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("a_income", models.DecimalField(decimal_places=2, max_digits=12)),
                ("b_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "salary_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "catchsale_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "public_assistance_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "alimony_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "dis_gis_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "retirement_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "disability_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "ignored_benefits_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "employer_paid_gl_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "foreign_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "civil_servant_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "other_pension_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "capital_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf.dataload",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf.person",
                    ),
                ),
                (
                    "person_month",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf.personmonth",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_entries",
                        to="bf.monthlyincomereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monthly income report",
                "verbose_name_plural": "historical monthly income reports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalMonthlyAIncomeReport",
        ),
        migrations.DeleteModel(
            name="HistoricalMonthlyBIncomeReport",
        ),
        migrations.DeleteModel(
            name="MonthlyAIncomeReport",
        ),
        migrations.DeleteModel(
            name="MonthlyBIncomeReport",
        ),
    ]
