# Generated by Django 5.1.3 on 2024-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0016_remove_historicalmonthlybincomereport_history_relation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prismebatchitem",
            name="error_code",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="error_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="invoice_no",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="posting_status_filename",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("posted", "Posted"), ("failed", "Failed")],
                db_index=True,
                default="sent",
            ),
        ),
    ]
