# Generated by Django 5.1.3 on 2024-12-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0017_prismebatchitem_error_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualincome",
            name="account_business_interest",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="account_business_interest_deduct",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="account_business_interest_income",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="account_extraord_entries_income",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="account_share_business_percentage",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="other_debt_interest_income",
        ),
        migrations.RemoveField(
            model_name="annualincome",
            name="social_benefit_income",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="account_business_interest",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="account_business_interest_deduct",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="account_business_interest_income",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="account_extraord_entries_income",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="account_share_business_percentage",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="other_debt_interest_income",
        ),
        migrations.RemoveField(
            model_name="historicalannualincome",
            name="social_benefit_income",
        ),
        migrations.AddField(
            model_name="annualincome",
            name="public_assistance_income",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="public_assistance_income",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
    ]
