# Generated by Django 5.1.3 on 2024-12-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0017_prismebatchitem_error_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BTaxPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_charged",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("date_charged", models.DateField()),
                ("rate_number", models.PositiveSmallIntegerField()),
                ("filename", models.TextField()),
                ("serial_number", models.PositiveBigIntegerField()),
                (
                    "person_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bf.personmonth"
                    ),
                ),
            ],
        ),
    ]
