# Generated by Django 5.1.3 on 2024-12-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0018_remove_annualincome_account_business_interest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonthlyincomereport",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bf.employer",
            ),
        ),
        migrations.AddField(
            model_name="monthlyincomereport",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bf.employer",
            ),
        ),
    ]
