# Generated by Django 5.1.3 on 2024-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0019_btaxpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        choices=[
                            ("calculate_stability_score", "Calculate Stability Score"),
                            (
                                "autoselect_estimation_engine",
                                "Autoselect Estimation Engine",
                            ),
                            ("load_eskat", "Load Eskat"),
                            ("estimate_income", "Estimate Income"),
                            ("calculate_benefit", "Calculate Benefit"),
                            ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                        ]
                    ),
                ),
                ("runtime", models.DateTimeField(auto_now_add=True)),
                ("year", models.IntegerField(default=None, null=True)),
                ("month", models.IntegerField(default=None, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("Kører", "Running"),
                            ("Gennemført", "Succeeded"),
                            ("Fejl", "Failed"),
                        ],
                        default="Kører",
                    ),
                ),
                ("year_param", models.IntegerField(default=None, null=True)),
                ("month_param", models.IntegerField(default=None, null=True)),
                ("count_param", models.IntegerField(default=None, null=True)),
                ("cpr_param", models.TextField(default=None, null=True)),
                ("type_param", models.TextField(default=None, null=True)),
                ("verbosity_param", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
