# Generated by Django 5.1.3 on 2024-12-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0021_historicalmonthlyincomereport_employer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmonthlyincomereport",
            name="person",
        ),
        migrations.RemoveField(
            model_name="monthlyincomereport",
            name="person",
        ),
    ]
