# Generated by Django 5.1.3 on 2024-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0022_remove_historicalmonthlyincomereport_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="traceback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
