# Generated by Django 5.1.3 on 2024-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0024_eboksmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="benefit_rate_percent",
            field=models.DecimalField(
                decimal_places=3, max_digits=5, verbose_name="Benefit rate percent"
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="max_benefit",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Max benefit"
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="personal_allowance",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Personal allowance"
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="scaledown_rate_percent",
            field=models.DecimalField(
                decimal_places=3, max_digits=5, verbose_name="Scaledown rate percent"
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="standard_allowance",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Standard allowance"
            ),
        ),
    ]
