# Generated by Django 5.1.3 on 2024-12-18 12:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0025_alter_standardworkbenefitcalculationmethod_benefit_rate_percent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonYearU1AAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u1a_ids",
                    models.CharField(
                        error_messages={
                            "invalid": "error.invalid_email",
                            "required": "error.required",
                        },
                        max_length=255,
                        verbose_name="U1A IDs i AKAP",
                    ),
                ),
                (
                    "dividend_total",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "invalid": "error.number_required",
                            "required": "error.required",
                        },
                        max_digits=12,
                        verbose_name="Udbetalt/godskrevet udbytte i DKK, før skat",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "load",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bf.dataload",
                    ),
                ),
                (
                    "person_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="u1a_assessments",
                        to="bf.personyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPersonYearU1AAssessment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "u1a_ids",
                    models.CharField(
                        error_messages={
                            "invalid": "error.invalid_email",
                            "required": "error.required",
                        },
                        max_length=255,
                        verbose_name="U1A IDs i AKAP",
                    ),
                ),
                (
                    "dividend_total",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "invalid": "error.number_required",
                            "required": "error.required",
                        },
                        max_digits=12,
                        verbose_name="Udbetalt/godskrevet udbytte i DKK, før skat",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf.dataload",
                    ),
                ),
                (
                    "person_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf.personyear",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_entries",
                        to="bf.personyearu1aassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical person year u1a assessment",
                "verbose_name_plural": "historical person year u1a assessments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
