# Generated by Django 5.1.3 on 2025-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0026_personyearu1aassessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomeestimate",
            name="income_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("U", "U")], default="A", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="personyearestimatesummary",
            name="income_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("U", "U")], default="A", max_length=1
            ),
        ),
    ]
