# Generated by Django 5.1.3 on 2025-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf", "0027_alter_incomeestimate_income_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
    ]
