# Generated by Django 5.0.4 on 2024-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineviewpreferences',
            name='show_TwoYearSummationEngine',
            field=models.BooleanField(default=True),
        ),
    ]
