# Generated by Django 5.0.4 on 2024-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_engineviewpreferences_show_twoyearsummationengine"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineviewpreferences",
            name="show_DeepLearningEngine",
            field=models.BooleanField(default=False),
        ),
    ]
