# Generated by Django 5.1.3 on 2025-01-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_engineviewpreferences_show_twoyearsummationengine"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cert_subject",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
