# Generated by Django 5.1.3 on 2025-01-15 15:42

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0002_alter_joblog_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonthlyincomereport",
            name="u_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyincomereport",
            name="u_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomeestimate",
            name="income_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("U", "U")], default="A", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="personyearestimatesummary",
            name="income_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("U", "U")], default="A", max_length=1
            ),
        ),
        migrations.CreateModel(
            name="PersonYearU1AAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "u1a_ids",
                    models.CharField(
                        error_messages={
                            "invalid": "error.invalid_email",
                            "required": "error.required",
                        },
                        max_length=255,
                        verbose_name="U1A IDs i AKAP",
                    ),
                ),
                (
                    "dividend_total",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "invalid": "error.number_required",
                            "required": "error.required",
                        },
                        max_digits=12,
                        verbose_name="Udbetalt/godskrevet udbytte i DKK, før skat",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "load",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suila.dataload",
                    ),
                ),
                (
                    "person_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="u1a_assessments",
                        to="suila.personyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPersonYearU1AAssessment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "u1a_ids",
                    models.CharField(
                        error_messages={
                            "invalid": "error.invalid_email",
                            "required": "error.required",
                        },
                        max_length=255,
                        verbose_name="U1A IDs i AKAP",
                    ),
                ),
                (
                    "dividend_total",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "invalid": "error.number_required",
                            "required": "error.required",
                        },
                        max_digits=12,
                        verbose_name="Udbetalt/godskrevet udbytte i DKK, før skat",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="suila.dataload",
                    ),
                ),
                (
                    "person_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="suila.personyear",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_entries",
                        to="suila.personyearu1aassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical person year u1a assessment",
                "verbose_name_plural": "historical person year u1a assessments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
