# Generated by Django 5.1.3 on 2025-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0004_note_historicalnote_noteattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="runtime_end",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
