# Generated by Django 5.1.3 on 2025-02-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0004_note_historicalnote_noteattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": (("view_data_analysis", "Can view data analysis"),)
            },
        ),
        migrations.AlterModelOptions(
            name="standardworkbenefitcalculationmethod",
            options={
                "permissions": (
                    (
                        "change_calculation_parameters",
                        "Can change calculation parameters",
                    ),
                )
            },
        ),
    ]
