# Generated by Django 5.1.3 on 2025-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0005_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prismebatchitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sendt"),
                    ("posted", "Bogført"),
                    ("failed", "Fejlet"),
                ],
                db_index=True,
                default="sent",
            ),
        ),
    ]
