# Generated by Django 5.1.3 on 2025-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0005_joblog_runtime_end"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": (("view_data_analysis", "Can view data analysis"),)
            },
        ),
        migrations.AlterModelOptions(
            name="standardworkbenefitcalculationmethod",
            options={
                "permissions": (
                    (
                        "change_calculation_parameters",
                        "Can change calculation parameters",
                    ),
                )
            },
        ),
        migrations.AlterField(
            model_name="prismebatchitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sendt"),
                    ("posted", "Bogført"),
                    ("failed", "Fejlet"),
                ],
                db_index=True,
                default="sent",
            ),
        ),
    ]
