# Generated by Django 5.1.3 on 2025-02-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0007_historicalpersonyearassessment_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standardworkbenefitcalculationmethod",
            options={
                "permissions": (
                    ("use_adminsite_calculator", "Can use adminsite calculator"),
                    (
                        "use_adminsite_calculator_parameters",
                        "Can use calculation parameters",
                    ),
                )
            },
        ),
    ]
