# Generated by Django 5.1.3 on 2025-02-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0008_alter_standardworkbenefitcalculationmethod_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eboksmessage",
            name="contents",
            field=models.FileField(null=True, upload_to="eboks"),
        ),
    ]
