# Generated by Django 5.1.3 on 2025-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0010_historicalpersonyearassessment_benefits_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prismeaccountalias",
            name="alias",
            field=models.TextField(),
        ),
    ]
