# Generated by Django 5.1.3 on 2025-02-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0010_historicalpersonyearassessment_benefits_income_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyearassessment",
            name="brutto_b_income",
        ),
        migrations.RemoveField(
            model_name="personyearassessment",
            name="brutto_b_income",
        ),
    ]
