# Generated by Django 5.1.3 on 2025-02-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0011_alter_prismeaccountalias_alias"),
        ("suila", "0011_historicalperson_welcome_letter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyearassessment",
            name="brutto_b_income",
        ),
        migrations.RemoveField(
            model_name="personyearassessment",
            name="brutto_b_income",
        ),
    ]
