# Generated by Django 5.1.3 on 2025-02-27 14:08

from django.db import migrations
from django.db import migrations, models

def rename(apps, from_name, to_name):

    IncomeEstimate = apps.get_model("suila", "IncomeEstimate")
    IncomeEstimate.objects.filter(engine=from_name).update(engine=to_name)

    PersonYearEstimateSummary = apps.get_model("suila", "PersonYearEstimateSummary")
    PersonYearEstimateSummary.objects.filter(estimation_engine=from_name).update(estimation_engine=to_name)

    PersonYear = apps.get_model("suila", "PersonYear")
    PersonYear.objects.filter(preferred_estimation_engine_a=from_name).update(preferred_estimation_engine_a=to_name)
    PersonYear.objects.filter(preferred_estimation_engine_b=from_name).update(preferred_estimation_engine_b=to_name)
    PersonYear.objects.filter(preferred_estimation_engine_u=from_name).update(preferred_estimation_engine_u=to_name)

    PersonYear.history.filter(preferred_estimation_engine_a=from_name).update(preferred_estimation_engine_a=to_name)
    PersonYear.history.filter(preferred_estimation_engine_b=from_name).update(preferred_estimation_engine_b=to_name)
    PersonYear.history.filter(preferred_estimation_engine_u=from_name).update(preferred_estimation_engine_u=to_name)



def apply(apps, schema_editor):
    rename(apps, "SameAsLastMonthEngine", "MonthlyContinuationEngine")

class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0012_remove_historicalpersonyearassessment_brutto_b_income_and_more"),
    ]

    operations = [

        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomeestimate",
            name="engine",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "SameAsLastMonthEngine",
                        "Ekstrapolation af beløb baseret udelukkende på den foregående måned",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),

        migrations.RunPython(apply),

        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomeestimate",
            name="engine",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
    ]
