# Generated by Django 5.1.3 on 2025-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0014_historicalperson_welcome_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualincome",
            name="account_share_business_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="account_tax_result",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="alimony_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="bond_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="care_fee_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="catch_sale_factory_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="catch_sale_market_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="deposit_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="dis_gis_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="disability_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="education_support_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="foreign_dividend_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="foreign_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="foreign_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_board_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_boat_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_car_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_housing_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_internet_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_journey_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_lodging_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_other_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="free_phone_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="group_life_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="ignored_benefits",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="occupational_benefit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="other_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="other_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="other_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="pension_payment_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="public_assistance_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="rental_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="retirement_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="shareholder_dividend_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annualincome",
            name="subsidy_foreign_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="account_share_business_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="account_tax_result",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="alimony_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="bond_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="care_fee_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="catch_sale_factory_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="catch_sale_market_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="deposit_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="dis_gis_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="disability_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="education_support_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="foreign_dividend_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="foreign_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="foreign_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_board_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_boat_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_car_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_housing_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_internet_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_journey_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_lodging_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_other_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="free_phone_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="group_life_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="ignored_benefits",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="occupational_benefit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="other_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="other_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="other_interest_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="pension_payment_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="public_assistance_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="rental_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="retirement_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="shareholder_dividend_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalannualincome",
            name="subsidy_foreign_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
    ]
