# Generated by Django 5.1.3 on 2025-03-07 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0016_alter_btaxpayment_person_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmonthlyincomereport",
            name="b_income",
        ),
        migrations.RemoveField(
            model_name="monthlyincomereport",
            name="b_income",
        ),
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="has_paid_b_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="b_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="b_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="catchsale_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyearassessment",
            name="latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="has_paid_b_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personyear",
            name="b_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="b_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="catchsale_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyearassessment",
            name="latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="SelfReportedEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_b",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                    ("SelfReportedEngine", "Estimering udfra forskudsopgørelsen"),
                ],
                default="SelfReportedEngine",
                max_length=100,
                null=True,
            ),
        ),
    ]
