# Generated by Django 5.1.3 on 2025-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0018_historicalpersonyearassessment_latest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="has_paid_b_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="has_paid_b_tax",
            field=models.BooleanField(default=False),
        ),
    ]
