# Generated by Django 5.1.3 on 2025-03-06 18:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0018_historicalpersonmonth_has_paid_b_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonyear",
            name="b_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="b_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonyear",
            name="catchsale_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="b_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="b_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="catchsale_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
