# Generated by Django 5.1.3 on 2025-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0019_remove_historicalmonthlyincomereport_b_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prismebatchitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sendt til udbetaling"),
                    ("posted", "Udbetaling gennemført"),
                    ("failed", "Fejl i udbetaling"),
                ],
                db_index=True,
                default="sent",
            ),
        ),
    ]
