# Generated by Django 5.1.3 on 2025-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0020_alter_prismebatchitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_b",
        ),
        migrations.RemoveField(
            model_name="personyear",
            name="preferred_estimation_engine_b",
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomeestimate",
            name="engine",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_a",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="InYearExtrapolationEngine",
                max_length=100,
                null=True,
            ),
        ),
    ]
