# Generated by Django 5.1.3 on 2025-03-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suila",
            "0021_remove_historicalpersonyear_preferred_estimation_engine_b_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SuilaEboksMessage",
            fields=[
                (
                    "eboksmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="suila.eboksmessage",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("opgørelse", "Opgørelse"), ("afventer", "Afventer")],
                        max_length=10,
                    ),
                ),
                (
                    "person_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suila.personmonth",
                    ),
                ),
            ],
            bases=("suila.eboksmessage",),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="welcome_letter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="suila.suilaeboksmessage",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="welcome_letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suila.suilaeboksmessage",
            ),
        ),
    ]
