# Generated by Django 5.1.3 on 2025-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0022_suilaeboksmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="foreign_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="foreign_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
