# Generated by Django 5.1.3 on 2025-03-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0023_historicalperson_country_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eboksmessage",
            name="xml",
        ),
    ]
