# Generated by Django 5.1.3 on 2025-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0024_remove_eboksmessage_xml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("eboks_send", "Send Eboks"),
                ]
            ),
        ),
    ]
