# Generated by Django 5.1.3 on 2025-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0025_alter_joblog_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="TwelveMonthsSummationEngine",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="preferred_estimation_engine_u",
            field=models.CharField(
                choices=[
                    (
                        "InYearExtrapolationEngine",
                        "Ekstrapolation af beløb for måneder i indeværende år",
                    ),
                    (
                        "TwelveMonthsSummationEngine",
                        "Summation af beløb for de seneste 12 måneder",
                    ),
                    (
                        "TwoYearSummationEngine",
                        "Summation af beløb for de seneste 24 måneder",
                    ),
                    (
                        "MonthlyContinuationEngine",
                        "Ekstrapolation af beløb for den seneste måned",
                    ),
                ],
                default="TwelveMonthsSummationEngine",
                max_length=100,
                null=True,
            ),
        ),
    ]
