# Generated by Django 5.1.3 on 2025-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0028_alter_joblog_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyear",
            name="paused",
        ),
        migrations.RemoveField(
            model_name="personyear",
            name="paused",
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
