# Generated by Django 5.1.3 on 2025-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0029_remove_historicalpersonyear_paused_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="can_unpause_himself",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="can_unpause_himself",
            field=models.BooleanField(default=True),
        ),
    ]
