# Generated by Django 5.1.3 on 2025-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0029_remove_historicalpersonyear_paused_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prismebatchitem",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
