# Generated by Django 5.1.3 on 2025-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0030_prismebatchitem_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="annual_income_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="annual_income_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
    ]
