# Generated by Django 5.1.3 on 2025-05-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0031_historicalperson_annual_income_estimate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrismePostingStatusFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.TextField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="prismebatchitem",
            name="posting_status_filename",
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="posting_status_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suila.prismepostingstatusfile",
            ),
        ),
    ]
