# Generated by Django 5.1.3 on 2025-05-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0031_historicalperson_annual_income_estimate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
