# Generated by Django 5.1.3 on 2025-05-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0032_historicalpersonmonth_paused_personmonth_paused"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblog",
            name="month",
        ),
        migrations.RemoveField(
            model_name="joblog",
            name="year",
        ),
    ]
