# Generated by Django 5.1.3 on 2025-05-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0033_remove_joblog_month_remove_joblog_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpersonmonth",
            old_name="benefit_paid",
            new_name="benefit_calculated",
        ),
        migrations.RenameField(
            model_name="historicalpersonmonth",
            old_name="prior_benefit_paid",
            new_name="prior_benefit_calculated",
        ),
        migrations.RenameField(
            model_name="personmonth",
            old_name="benefit_paid",
            new_name="benefit_calculated",
        ),
        migrations.RenameField(
            model_name="personmonth",
            old_name="prior_benefit_paid",
            new_name="prior_benefit_calculated",
        ),
    ]
