# Generated by Django 5.1.3 on 2025-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0036_btaxpayment_cpr_btaxpayment_unique_btaxpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonmonth",
            name="prior_benefit_calculated",
        ),
        migrations.RemoveField(
            model_name="personmonth",
            name="prior_benefit_calculated",
        ),
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="benefit_transferred",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="prior_benefit_transferred",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="benefit_transferred",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="prior_benefit_transferred",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
