# Generated by Django 5.1.3 on 2025-05-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0038_populate_benefit_transferred"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrismePostingStatusFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.TextField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="prismebatchitem",
            name="posting_status_filename",
        ),
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("load_prisme_b_tax", "Load Prisme B Tax"),
                    ("import_u1a_data", "Import U1A Data"),
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("eboks_send", "Send Eboks"),
                    (
                        "load_prisme_benefits_posting_status",
                        "Load Prisme Benefits Posting Status",
                    ),
                ]
            ),
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="posting_status_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suila.prismepostingstatusfile",
            ),
        ),
    ]
