# Generated by Django 5.1.3 on 2025-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0038_populate_benefit_transferred"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="cpr_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="cpr_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
