# Generated by Django 5.1.3 on 2025-06-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0042_alter_joblog_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prismebatch",
            options={
                "permissions": (("can_download_reports", "Can download CSV reports"),)
            },
        ),
    ]
