# Generated by Django 5.1.3 on 2025-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0043_alter_prismebatch_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="skew_param",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
