# Generated by Django 5.1.3 on 2025-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0044_joblog_skew_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="benefit_rate_percent",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Den procentdel af indkomstgrundlaget, der anvendes til at beregne den udbetalte værdi af Suila-tapit.",
                max_digits=5,
                verbose_name="Procentsats for Suila-tapit",
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="max_benefit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Den maksimale årlige Suila-tapit ydelse.",
                max_digits=12,
                verbose_name="Maksimalt Suila-tapit",
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="personal_allowance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Et skattefrit beløb, som alle personer har ret til at fratrække deres indkomst, før skatten beregnes.",
                max_digits=12,
                verbose_name="Personfradrag",
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="scaledown_ceiling",
            field=models.DecimalField(
                decimal_places=2,
                help_text="For personer, der tjener mere end den fastsatte aftrapningsbeløbet, skal Suila-tapit nedtrappes med den fastsatte aftrapningsprocent.",
                max_digits=12,
                verbose_name="Aftrapningsbeløb",
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="scaledown_rate_percent",
            field=models.DecimalField(
                decimal_places=3,
                help_text="For personer, der tjener mere end det fastsatte aftrapningsbeløb, skal Suila-tapit nedtrappes til den fastsatte aftrapningsprocent.",
                max_digits=5,
                verbose_name="Aftrapningsprocent",
            ),
        ),
        migrations.AlterField(
            model_name="standardworkbenefitcalculationmethod",
            name="standard_allowance",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Standardfradrag"
            ),
        ),
    ]
