# Generated by Django 5.1.3 on 2025-07-22 08:35

import django.db.models.deletion
import suila.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suila",
            "0045_alter_standardworkbenefitcalculationmethod_benefit_rate_percent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxInformationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Startdato")),
                ("end_date", models.DateTimeField(verbose_name="Slutdato")),
                ("tax_scope", models.CharField(verbose_name="Skattepligtighed")),
                (
                    "person_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suila.personyear",
                    ),
                ),
            ],
            options={
                "unique_together": {("person_year", "start_date", "end_date")},
            },
            bases=(suila.model_mixins.PermissionsMixin, models.Model),
        ),
    ]
