# Generated by Django 5.1.3 on 2025-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0047_taxinformationperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="allow_pause",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="allow_pause",
            field=models.BooleanField(default=True),
        ),
    ]
