# Generated by Django 5.1.3 on 2025-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0048_historicalperson_allow_pause_person_allow_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="pause_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Indikation af urigtige oplysninger i forskudsregistrering"),
                    (
                        2,
                        "Indikation af fejl i beregningsgrundlag - fejl i oplysninger fra indberetter",
                    ),
                    (
                        3,
                        "Indikation af fejl i beregningsgrundlag - manglende indberetninger",
                    ),
                    (4, "Indikation af ændringer i forventet årsindkomst"),
                    (5, "Indikation af ændringer i skattepligt til Grønland"),
                    (6, "Indikation af systemfejl"),
                    (7, "Efter aftale med borgeren eller dennes repræsentant"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="pause_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Indikation af urigtige oplysninger i forskudsregistrering"),
                    (
                        2,
                        "Indikation af fejl i beregningsgrundlag - fejl i oplysninger fra indberetter",
                    ),
                    (
                        3,
                        "Indikation af fejl i beregningsgrundlag - manglende indberetninger",
                    ),
                    (4, "Indikation af ændringer i forventet årsindkomst"),
                    (5, "Indikation af ændringer i skattepligt til Grønland"),
                    (6, "Indikation af systemfejl"),
                    (7, "Efter aftale med borgeren eller dennes repræsentant"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
