# Generated by Django 5.1.3 on 2025-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0049_historicalperson_pause_reason_person_pause_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="output",
            field=models.TextField(default=None, null=True),
        ),
    ]
