# Generated by Django 5.1.3 on 2025-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0049_historicalperson_pause_reason_person_pause_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suilaeboksmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("opgørelse", "Opgørelse"),
                    ("afventer", "Afventer"),
                    ("payout_pause", "Udbetalingspause"),
                ],
                max_length=12,
            ),
        ),
    ]
