# Generated by Django 5.1.3 on 2025-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0050_alter_historicalperson_pause_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suilaeboksmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("opgørelse", "Opgørelse"),
                    ("afventer", "Afventer"),
                    ("payout_pause", "Udbetalingspause"),
                ],
                max_length=12,
            ),
        ),
    ]
