# Generated by Django 5.1.3 on 2025-09-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0052_alter_historicalperson_pause_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyear",
            name="tax_scope",
        ),
        migrations.RemoveField(
            model_name="personyear",
            name="tax_scope",
        ),
    ]
