# Generated by Django 5.1.3 on 2025-09-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0053_joblog_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonyear",
            name="tax_scope",
        ),
        migrations.RemoveField(
            model_name="personyear",
            name="tax_scope",
        ),
    ]
