# Generated by Django 5.1.3 on 2025-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0055_joblog_since_param_alter_joblog_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblog",
            name="since_param",
        ),
    ]
