# Generated by Django 5.1.3 on 2025-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0056_remove_joblog_since_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eboksmessage",
            name="recipient_status",
            field=models.CharField(
                choices=[
                    ("", "Gyldig e-Boks modtager"),
                    ("exempt", "Fritaget modtager"),
                    ("invalid", "Ugyldig E-boks modtager (sendes til efterbehandling)"),
                    ("dead", "Afdød"),
                    ("minor", "Mindreårig"),
                ],
                max_length=8,
            ),
        ),
    ]
