# Generated by Django 5.1.3 on 2025-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0056_remove_joblog_since_param"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["cpr"], name="suila_perso_cpr_5d3455_idx"),
        ),
    ]
