# Generated by Django 5.1.3 on 2025-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0057_person_suila_perso_cpr_5d3455_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eboksmessage",
            name="recipient_status",
            field=models.CharField(
                choices=[
                    ("", "Gyldig e-Boks modtager"),
                    ("exempt", "Fritaget modtager"),
                    ("invalid", "Ugyldig E-boks modtager (sendes til efterbehandling)"),
                    ("dead", "Afdød"),
                    ("minor", "Mindreårig"),
                ],
                max_length=8,
            ),
        ),
    ]
