# Generated by Django 5.1.3 on 2025-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0057_person_suila_perso_cpr_5d3455_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "Ingen"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Du tjente for tæt på bundgrænsen i {year}"),
                    (3, "Du tjente for tæt på øverste grænse i {year}"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "Ingen"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Du tjente for tæt på bundgrænsen i {year}"),
                    (3, "Du tjente for tæt på øverste grænse i {year}"),
                ],
                default=0,
            ),
        ),
    ]
