# Generated by Django 5.1.3 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0058_alter_eboksmessage_recipient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "-"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Du tjente for tæt på bundgrænsen i {year}"),
                    (3, "Du tjente for tæt på øverste grænse i {year}"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="personyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "-"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Du tjente for tæt på bundgrænsen i {year}"),
                    (3, "Du tjente for tæt på øverste grænse i {year}"),
                ],
                default=0,
            ),
        ),
    ]
