# Generated by Django 5.1.3 on 2025-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0059_historicalpersonyear_quarantine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="status",
            field=models.TextField(
                choices=[
                    ("Kører", "Running"),
                    ("Gennemført", "Succeeded"),
                    ("Fejl", "Failed"),
                    ("Afhængigheder ikke opfyldt", "Dependencies Not Met"),
                ],
                default="Kører",
            ),
        ),
    ]
