# Generated by Django 5.1.3 on 2025-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0060_alter_joblog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="save_param",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="joblog",
            name="send_param",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
