# Generated by Django 5.1.3 on 2026-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0061_joblog_save_param_joblog_send_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "-"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Din forventede årsindkomst er tæt på Suila-tapit grænsen"),
                    (3, "Din forventede årsindkomst er tæt på Suila-tapit grænsen"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="personyear",
            name="quarantine",
            field=models.IntegerField(
                choices=[
                    (0, "-"),
                    (1, "Du modtog for meget tilskud i {year}"),
                    (2, "Din forventede årsindkomst er tæt på Suila-tapit grænsen"),
                    (3, "Din forventede årsindkomst er tæt på Suila-tapit grænsen"),
                ],
                default=0,
            ),
        ),
    ]
