# Generated by Django 5.1.3 on 2026-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0062_alter_historicalpersonyear_quarantine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualincome",
            name="summarized_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="annualincome",
            name="summarized_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="annualincome",
            name="summarized_u_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_u_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
    ]
