# Generated by Django 5.2.8 on 2026-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0063_alter_joblog_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualincome",
            name="summarized_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="annualincome",
            name="summarized_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="annualincome",
            name="summarized_u_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_a_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_b_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="summarized_u_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("load_prisme_b_tax", "Load Prisme B Tax"),
                    ("import_u1a_data", "Import U1A Data"),
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    (
                        "get_updated_person_info_from_dafo",
                        "Get Updated Person Info From Dafo",
                    ),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("send_monthly_eboks_message", "Send Monthly Eboks"),
                    ("send_yearly_eboks_message", "Send Yearly Eboks"),
                    (
                        "load_prisme_benefits_posting_status",
                        "Load Prisme Benefits Posting Status",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="suilaeboksmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("opgørelse", "Opgørelse"),
                    ("årsopgørelse", "Årsopgørelse"),
                    ("afventer", "Afventer"),
                    ("payout_pause", "Udbetalingspause"),
                ],
                max_length=12,
            ),
        ),
    ]
