# Generated by Django 5.2.16 on 2026-07-15 12:36

import django.db.models.deletion
import suila.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0064_annualincome_summarized_a_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("load_prisme_b_tax", "Load Prisme B Tax"),
                    ("import_u1a_data", "Import U1A Data"),
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    (
                        "get_updated_person_info_from_dafo",
                        "Get Updated Person Info From Dafo",
                    ),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("send_monthly_eboks_message", "Send Monthly Eboks"),
                    ("generate_final_settlements", "Generate Final Settlements"),
                    (
                        "load_prisme_benefits_posting_status",
                        "Load Prisme Benefits Posting Status",
                    ),
                ]
            ),
        ),
        migrations.CreateModel(
            name="FinalSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("_pdf", models.FileField(null=True, upload_to="aarsopgoerelse")),
                (
                    "_result",
                    models.DecimalField(decimal_places=2, default=None, max_digits=12),
                ),
                (
                    "annual_income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_settlements",
                        to="suila.annualincome",
                    ),
                ),
                (
                    "eboks_message",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suila.suilaeboksmessage",
                    ),
                ),
            ],
            bases=(suila.model_mixins.PermissionsMixin, models.Model),
        ),
    ]
