# Generated by Django 5.2.17 on 2026-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0065_alter_joblog_name_finalsettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
    ]
