# Generated by Django 5.2.17 on 2026-08-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0065_alter_joblog_name_finalsettlement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prismebatchitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="final_settlement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.finalsettlement",
            ),
        ),
        migrations.AlterField(
            model_name="prismebatchitem",
            name="person_month",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.personmonth",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prismebatchitem",
            unique_together={("prisme_batch", "person_month", "final_settlement")},
        ),
    ]
