# Generated by Django 5.2.17 on 2026-08-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0065_alter_joblog_name_finalsettlement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prismebatchitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="final_settlement",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.finalsettlement",
            ),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("load_prisme_b_tax", "Load Prisme B Tax"),
                    ("import_u1a_data", "Import U1A Data"),
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    (
                        "get_updated_person_info_from_dafo",
                        "Get Updated Person Info From Dafo",
                    ),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("send_monthly_eboks_message", "Send Monthly Eboks"),
                    ("generate_final_settlements", "Generate Final Settlements"),
                    (
                        "load_prisme_benefits_posting_status",
                        "Load Prisme Benefits Posting Status",
                    ),
                    (
                        "export_final_settlements_to_prisme",
                        "Export Final Settlements To Prisme",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="prismebatchitem",
            name="person_month",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.personmonth",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prismebatchitem",
            unique_together={("prisme_batch", "person_month", "final_settlement")},
        ),
    ]
