# Generated by Django 5.2.17 on 2026-08-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0066_alter_prismebatchitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualincome",
            name="employer_paid_gl_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalannualincome",
            name="employer_paid_gl_pension_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="finalsettlement",
            name="eboks_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suila.suilaeboksmessage",
            ),
        ),
    ]
