# Generated by Django 5.2.17 on 2026-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0066_alter_prismebatchitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="name",
            field=models.TextField(
                choices=[
                    ("calculate_stability_score", "Calculate Stability Score"),
                    ("autoselect_estimation_engine", "Autoselect Estimation Engine"),
                    ("load_eskat", "Load Eskat"),
                    ("load_prisme_b_tax", "Load Prisme B Tax"),
                    ("import_u1a_data", "Import U1A Data"),
                    ("get_person_info_from_dafo", "Get Person Info From Dafo"),
                    (
                        "get_updated_person_info_from_dafo",
                        "Get Updated Person Info From Dafo",
                    ),
                    ("estimate_income", "Estimate Income"),
                    ("calculate_benefit", "Calculate Benefit"),
                    ("export_benefits_to_prisme", "Export Benefits To Prisme"),
                    ("send_monthly_eboks_message", "Send Monthly Eboks"),
                    ("generate_final_settlements", "Generate Final Settlements"),
                    (
                        "load_prisme_benefits_posting_status",
                        "Load Prisme Benefits Posting Status",
                    ),
                    (
                        "export_final_settlements_to_prisme",
                        "Export Final Settlements To Prisme",
                    ),
                ]
            ),
        ),
    ]
