# Generated by Django 5.2.17 on 2026-09-10 12:36

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_person_year(apps, schema_editor):
    # Årsopgørelse messages used to point at the latest person_month of the year.
    # They now point at the person_year directly, so copy it over. Without this,
    # generate_final_settlements would consider these person_years to be without
    # an årsopgørelse and generate a duplicate message.
    SuilaEboksMessage = apps.get_model("suila", "SuilaEboksMessage")

    messages = list(
        SuilaEboksMessage.objects.filter(
            type="årsopgørelse",
            person_month__isnull=False,
            person_year__isnull=True,
        ).select_related("person_month")
    )

    logger.info(f"Backfilling person_year on {len(messages)} årsopgørelse messages")

    for message in messages:
        message.person_year_id = message.person_month.person_year_id

    SuilaEboksMessage.objects.bulk_update(messages, ["person_year"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0067_annualincome_employer_paid_gl_pension_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suilaeboksmessage",
            name="person_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.personyear",
            ),
        ),
        migrations.AlterField(
            model_name="suilaeboksmessage",
            name="person_month",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suila.personmonth",
            ),
        ),
        migrations.RunPython(backfill_person_year, migrations.RunPython.noop),
    ]
