# Generated by Django 5.2.17 on 2026-09-02 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0067_annualincome_employer_paid_gl_pension_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="benefit_difference",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="offset_benefit_difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="benefit_difference",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="offset_benefit_difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
