# Generated by Django 5.2.17 on 2026-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0068_suilaeboksmessage_person_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="red_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
