# Generated by Django 5.2.17 on 2026-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0068_suilaeboksmessage_person_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
    ]
