# Generated by Django 5.2.17 on 2026-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0069_recalculate_a_income_with_foreign_pension"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="rec_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
