# Generated by Django 5.2.17 on 2026-09-17 13:04

from decimal import Decimal
from django.db import migrations, models
from common.model_utils import get_amount_from_g68_content


def set_amount_from_g68_data(apps, schema_editor):
    PrismeBatchItem = apps.get_model("suila", "PrismeBatchItem")
    prismebatchitems = PrismeBatchItem.objects.filter(
        final_settlement__isnull=False,
        _amount__isnull=True,
    )
    for prismebatchitem in prismebatchitems:
        prismebatchitem._amount = get_amount_from_g68_content(
            prismebatchitem.g68_content
        )
        prismebatchitem.save(update_fields=["_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("suila", "0070_finalsettlement_invoice_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="benefit_difference",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonmonth",
            name="offset_benefit_difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="benefit_difference",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="personmonth",
            name="offset_benefit_difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="prismebatchitem",
            name="_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.RunPython(
            set_amount_from_g68_data
        )
    ]
